[build]
  command = "npm run build"
  publish = "dist"

# Proxy API => ingen CORS i prod (samme origin)
[[redirects]]
  from = "/api/*"
  to   = "https://DIN-BACKEND-URL/:splat"
  status = 200
  force = true

# SPA: send alt til index.html
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Cache statiske assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Sikkerhetsoverskrifter
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://DIN-BACKEND-URL; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self'; font-src 'self' data:"